name: Deploy to GitHub Pages

# 触发条件: 当 docs 分支有推送时运行
on:
  push:
    branches:
      - docs  # 监听 docs 分支的推送

# 权限配置
permissions:
  contents: write  # 允许写入 main 分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm build:package

      - name: Docs build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm docs:build

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: docs/.vuepress/dist
          single-commit: true
