name: Deploy to GitHub Pages

on:
  push:
    branches:
      - docs  # 监听 docs 分支的推送

permissions:
  contents: write  # 允许写入 main 分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的历史记录

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'  # 使用 yarn 缓存
      
      # Step 3: 安装依赖
      - name: Install dependencies
        run: yarn install
        
      # Step 4: 构建文档
      - name: Build VuePress
        run: yarn docs:build

      - name: 检查 GitHub Pages Deploy Action 安装
        run: ls -la ${{ github.workspace }}/_actions/JamesIves/github-pages-deploy-action/v4/lib/

      # Step 5: 部署到 main 分支
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # 部署到 main 分支
          folder: docs/.vuepress/dist  # 使用 dist 目录作为静态文件源
          clean: true  # 清理 main 分支根目录中的文件
